{% set name = "digdem" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/digdem-{{ version }}.tar.gz
  sha256: 293a3e835aca82e2a1fd2d07e61c79b004a46209211b709747016f62822591f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - shapely
    - geopandas
    - requests
    - scipy
    - matplotlib-base
    - rasterio

test:
  imports:
    - digdem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/marcperuz/digdem
  summary: Semi-automated modification of Digital Elevation Models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcperuz
