{% set name = "digdem" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/digdem-{{ version }}.tar.gz
  sha256: b160e031a27694375446117b2d9a3ce221744a7e6cf88f92519051a026d6f096

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - shapely
    - geopandas
    - requests
    - scipy
    - matplotlib-base
    - rasterio

test:
  imports:
    - digdem
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/marcperuz/digdem
  summary: Semi-automated modification of Digital Elevation Models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcperuz
